micronaut:
  application:
    name: search-api
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
    enabled: false

search-api:
  solr:
    url: http://localhost:8983/solr
    authentication:
      enabled: false
      type: jwt
      client-secret: my-client-secret
      client-id: my-client-id
      issuer: https://my-token-url.com/oauth2/some-token/v1/token
      issuerAuthId: issuer-auth-id
      subject: your-subject
      scope: solr # scope requested for oauth
      require-dpop: true # true if we are to include dpop proof to the server
      proxy-settings:
        enabled: true
        host: localhost
        port: 8080
    collection-config:
      collection-name: documents
      keyword-query-fields:
        - body
        - title
        - keyword
      vector-fields:
        body:
          field-name: body
          vector-field-name: body-vector
          chunk-field: true
          chunk-collection: body-vector
          vector-grpc-service: http://localhost:50401/vectorizer
          k: 10
        title:
          field-name: title
          vector-field-name: title-vector
          chunk-field: false
          vector-grpc-service: http://localhost:50401/vectorizer
          k: 10



