micronaut:
  application:
    name: search-api
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
    enabled: false

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
search-api:
  vector-grpc-channel: http://localhost:50401
  solr:
    url: http://localhost:8983/solr
    authentication:
      enabled: false
      type: jwt
      client-secret: my-client-secret
      client-id: my-client-id
      issuer: https://my-token-url.com/oauth2/some-token/v1/token
      issuerAuthId: issuer-auth-id
      subject: your-subject
      scope: solr
      require-dpop: true
      proxy-settings:
        enabled: true
        host: localhost
        port: 8080
    grpc-timeout: 5000 # Timeout for gRPC calls in milliseconds
    default-search:
      rows: 30
      sort: "score desc"
      default-query-type: semantic
      parse-boosted-queries: true
    caching:
      enabled: true
      ttl: 300
    error-handling:
      log-level: error
      retry-attempts: 3
    vector-configuration:
      default-dimensions: 384
      algorithm: "cosine"
    collection-config:
      collection-name: documents
      keyword-query-fields:
        - body
        - title
      vector-fields:
        bodyVectorField:
          field-name: body
          vector-field-name: body-vector
          vector-field-type: inline
          chunk-collection: body-vector
          vector-grpc-service: http://localhost:50401/vectorizer
          k: 10
        titleVectorField:
          field-name: title
          vector-field-name: title-vector
          vector-field-type: inline
          vector-grpc-service: http://localhost:50401/vectorizer
          k: 10
          