micronaut:
  caches:
    vectorCache:
      maximum-size: 1000
      expire-after-write: 1h
  jcache:
    enabled: true
  application:
    name: search-api
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    cors:
      enabled: true
      configurations:
        all:
          allowedOrigins:
            - "http://localhost:3000"
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowedHeaders:
            - "Content-Type"
            - "Accept"
            - "Authorization"
          maxAge: 3600
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
    enabled: false

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
search-api:
  vector-default:
    vector-cache-location: ./vector-cache
    vector-grpc-channel: ${sys:search-api.vector-default.vector-grpc-channel} # Dynamically set via system property
    vector-grpc-display-name: all-Mini-LM-embeddings-384
  solr:
    url: http://localhost:8983/solr
    authentication:
      enabled: false
      type: jwt
      client-secret: my-client-secret
      client-id: my-client-id
      issuer: https://my-token-url.com/oauth2/some-token/v1/token
      issuerAuthId: issuer-auth-id
      subject: your-subject
      scope: solr
      require-dpop: true
      proxy-settings:
        enabled: true
        host: localhost
        port: 8080
    default-search:
      rows: 30
      sort: "score desc"
      search-type: semantic
      debug: false
      include-fields:
        - title
        - body
      exclude-fields:
        - body-paragraphs
    collection-config:
      collection-name: documents
      keyword-query-fields:
        - body
        - title
      vector-fields:
        bodyVectorField:
          field-name: body
          vector-field-name: body-vector
          vector-field-type: inline
          chunk-collection: body-vector
          vector-grpc-service: http://localhost:50401/vectorizer
          k: 10
        titleVectorField:
          field-name: title
          vector-field-name: title-vector
          vector-field-type: inline
          vector-grpc-service: http://localhost:50401/vectorizer
          k: 10
